apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
        - name: explorer
          image: sysrex/explorer
      tolerations:
        - effect: NoSchedule
          key: dedicated
          value: ops-team
